#   <StarRailAssistant:An automated program that helps you complete daily tasks of StarRail.>
#   Copyright © <2024> <Shasnow>

#   This file is part of StarRailAssistant.

#   StarRailAssistant is free software: you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free Software Foundation,
#   either version 3 of the License, or (at your option) any later version.

#   StarRailAssistant is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#   without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#   See the GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License along with StarRailAssistant.
#   If not, see <https://www.gnu.org/licenses/>.

#   yukikage@qq.com

name: Build StarRailAssistant

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Node dependencies
        run: npm install
        
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false
        
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Build Python package
        run: |
          cd SRA-CE-cli
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          python package.py
          cd ..
          
      - name: Read version and channel
        id: read_info
        run: |
          $VERSION=(Get-Content -Path "package.json" | ConvertFrom-Json).version
          $CHANNEL=(Get-Content -Path "information.md" -TotalCount 1).Replace("channel:", "").Trim()
          "version=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Append
          "channel=$CHANNEL" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Version: $VERSION"
          echo "Channel: $CHANNEL"
          
      - name: Install Inno Setup
        run: |
          choco install innosetup --no-progress --yes
          
      - name: Build project
        run: npm run package
          
      - name: Upload zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StarRailAssistant-Core-${{ env.version }}
          path: src-setup/output/StarRailAssistant-Core-${{ env.version }}.zip
          
      - name: Upload Setup Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StarRailAssistant_${{ env.version }}_setup
          path: src-setup/output/StarRailAssistant_${{ env.version }}_Setup.exe
          
  publish_release:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: StarRailAssistant*
          merge-multiple: true
          path: artifacts
          
      - name: Read version and channel
        id: read_info
        run: |
          VERSION=$(jq -r '.version' package.json)
          CHANNEL=$(head -n 1 information.md | sed 's/channel://g' | sed 's/\r$//g' | xargs)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "channel=$CHANNEL" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
          echo "Channel: $CHANNEL"
          
      - name: Prepare release notes
        id: prepare_notes
        run: |
          NOTES=$(tail -n +4 information.md)
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "---" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "Setup.exe - 程序安装包 (Program Installer)" >> $GITHUB_OUTPUT
          echo "Core.zip - 后端核心程序 (Backend Core Program)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Check if release exists
        id: check_if_release_exists
        run: |
          release_id=$(gh release view "v${{ steps.read_info.outputs.version }}" --json id --jq .id || true)
          if [[ -z $release_id ]]; then
            echo "release_exists=false" >> $GITHUB_OUTPUT
          else
            echo "release_exists=true" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          
      - name: Create release
        id: create_release
        if: steps.check_if_release_exists.outputs.release_exists == 'false'
        run: |
          set -xe
          shopt -s nullglob
          TAGNAME="v${{ steps.read_info.outputs.version }}"
          CHANNEL="${{ steps.read_info.outputs.channel }}"
          
          if [[ "$CHANNEL" == "beta" ]]; then
            gh release create "$TAGNAME" --target "main" --title "$TAGNAME" --notes "${{ steps.prepare_notes.outputs.notes }}" --prerelease artifacts/*
          else
            gh release create "$TAGNAME" --target "main" --title "$TAGNAME" --notes "${{ steps.prepare_notes.outputs.notes }}" artifacts/*
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          
      - name: Update release
        if: steps.check_if_release_exists.outputs.release_exists == 'true'
        run: |
          set -xe
          shopt -s nullglob
          TAGNAME="v${{ steps.read_info.outputs.version }}"
          CHANNEL="${{ steps.read_info.outputs.channel }}"
          
          gh release delete "$TAGNAME" --yes
          
          if [[ "$CHANNEL" == "beta" ]]; then
            gh release create "$TAGNAME" --target "main" --title "$TAGNAME" --notes "${{ steps.prepare_notes.outputs.notes }}" --prerelease artifacts/*
          else
            gh release create "$TAGNAME" --target "main" --title "$TAGNAME" --notes "${{ steps.prepare_notes.outputs.notes }}" artifacts/*
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
